cc_library(
    name='hiho',
    hdrs=glob(['*.h']),
    srcs=glob(['*.cc']),
    copts=[
        "-std=c++17",
        "-march=native",
        "-Ofast",
        "-Wall",
        "-flto",
    ],
    linkopts=[
        "-fuse-ld=lld",
    ],
    visibility=["//visibility:public"],
)
